import "@/assets/styles/globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import type { Metadata } from "next";
import { Inter, Prompt } from "next/font/google";
import { PropsWithChildren } from "react";
import "react-toastify/dist/ReactToastify.css";
import "/node_modules/flag-icons/css/flag-icons.min.css";
import { ToastContainer } from "react-toastify";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const prompt = Prompt({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin", "thai"],
  display: "swap",
  variable: "--font-prompt",
});

export const metadata: Metadata = {
  title: "Next13 App",
  description: "Generated by create next app",
};

export default async function AppLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={`${inter.variable} ${prompt.variable}`}>
      <body>
        <ThemeProvider>{children}</ThemeProvider>
        <ToastContainer className="toast-container__custom" />
      </body>
    </html>
  );
}
