import "@/assets/styles/globals.css";
import LocaleAndMode from "@/components/locale-and-mode";
import ToastProvider from "@/providers/toast-provider";
import type { Metadata } from "next";
import { Inter, Prompt } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const prompt = Prompt({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin", "thai"],
  display: "swap",
  variable: "--font-prompt",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${prompt.variable}`}>
      <body>
        <ToastProvider>
          <LocaleAndMode />
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
