import LocaleSwitcher from "@/components/locale-switcher";
import { languages } from "@/configs/language-config";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { Prompt } from "next/font/google";
import { notFound } from "next/navigation";
import { PropsWithChildren } from "react";
import { ToastContainer } from "react-toastify";

const prompt = Prompt({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin", "thai"],
  display: "swap",
  variable: "--font-prompt",
});

export const metadata: Metadata = {
  title: "Next13",
  description: "Generated by create next app",
};

type LocaleLayoutProps = {
  params: { locale: Locale };
};

async function getMessages(locale: Locale) {
  try {
    return (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }
}

export async function generateStaticParams() {
  return languages.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params: { locale },
}: PropsWithChildren<LocaleLayoutProps>) {
  const messages = await getMessages(locale);

  return (
    <html lang={locale} className={prompt.variable}>
      <body>
        <LocaleSwitcher />
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
          <ToastContainer className="toast-container__custom" />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
