import LocaleAndTheme from "@/components/locale-and-theme";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { PropsWithChildren } from "react";

export const metadata: Metadata = {
  title: "Next13",
  description: "Generated by create next app",
};

type LocaleLayoutProps = {
  params: { locale: Locale };
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: PropsWithChildren<LocaleLayoutProps>) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <NextIntlClientProvider locale={locale} messages={messages}>
      <LocaleAndTheme locale={locale} />
      {children}
    </NextIntlClientProvider>
  );
}
