import LocaleSwitcher from "@/components/locale-switcher";
import { languages } from "@/configs/language-config";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { PropsWithChildren } from "react";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Next13",
  description: "Generated by create next app",
};

type LocaleLayoutProps = {
  params: { locale: Locale };
};

async function getMessages(locale: Locale) {
  try {
    return (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }
}

export async function generateStaticParams() {
  return languages.map((locale) => ({ locale }));
}

export default async function HomeLayout({
  children,
  params: { locale },
}: PropsWithChildren<LocaleLayoutProps>) {
  const messages = await getMessages(locale);

  return (
    <NextIntlClientProvider locale={locale} messages={messages}>
      <LocaleSwitcher />
      {children}
      <ToastContainer className="toast-container__custom" />
    </NextIntlClientProvider>
  );
}
